### ISSUE TITLE
Can't install 0.132 due to an unreleased dependency

### ISSUE THREAD

**Issue by chocolateboy** [perlancar/perl-Media-Info#1]
Media::Info 0.132 depends on [Filename::Image 0.002](https://github.com/perlancar/perl-Media-Info/blob/473d31ef6c1df264a65744234a04d59229512899/dist.ini#L18), which hasn't been released yet:

```
$ cpanm Media::Info
...
Found Filename::Image 0.001 which doesn't satisfy 0.002.
! Installing the dependencies failed: Installed version (0.001) of Filename::Image is not in range '0.002'
! Bailing out the installation for Media-Info-0.132.
```

```
$ wget --quiet -O- https://fastapi.metacpan.org/v1/module/Filename::Image | jq .version
"0.001"
```

**Comment by perlancar** [comment]
Sorry for the late response, didn't see the notification.

I believe this has been resolved by time.
